package UI; 

import Logic.Usuario;
import java.awt.Color;
import java.awt.Image;
import java.lang.reflect.Array;
import java.util.Arrays;
import javax.swing.DefaultListModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;


/**
 *
 * @author Stirven
 */
public class Frame extends javax.swing.JFrame { 
    Slide slide;
    Usuario user;
    int xMouse;
    int yMouse;
    private int plataStado=0;
    DefaultListModel model = new DefaultListModel();
    DefaultListModel model2 = new DefaultListModel();
    // String str ="aa";
    // String str = new String(null);
    /**
     * Creates new form main
     */
    public Frame() { 
        initComponents();
        slide = new Slide();
        
        imgLabel(eliminarUsuario,"src\\UI\\ico\\eliminarUser.png");
        imgLabel(cerarLogin,"src\\UI\\ico\\cerrar.png");
        imgLabel(cerarRegistro,"src\\UI\\ico\\cerrar.png");
        imgLabel(cerarInicio,"src\\UI\\ico\\cerrar.png");
        imgLabel(dinero_inicio,"src\\UI\\ico\\dienro.png");
        imgLabel(editarInfoBoton,"src\\UI\\ico\\info.png");
        imgLabel(historialBoton,"src\\UI\\ico\\historial.png");
        imgLabel(salir,"src\\UI\\ico\\salir.png");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textButonEstilo = new javax.swing.JLabel();
        logoStilo = new javax.swing.JLabel();
        TextFieldEstilo = new javax.swing.JTextField();
        eliminarUsuario = new javax.swing.JLabel();
        fondoLogin = new javax.swing.JPanel();
        Loguin = new javax.swing.JPanel();
        usuarioLogin = new javax.swing.JTextField();
        contraseñaLogin = new javax.swing.JPasswordField();
        logo1 = new javax.swing.JLabel();
        Entrar1 = new javax.swing.JButton();
        Reguistrarse1 = new javax.swing.JButton();
        alerta_login = new javax.swing.JLabel();
        cerarLogin = new javax.swing.JLabel();
        userListPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList<>();
        fondo = new javax.swing.JLabel();
        fondoInicio = new javax.swing.JPanel();
        Inicio = new javax.swing.JPanel();
        nombre_pg1 = new javax.swing.JLabel();
        logo3 = new javax.swing.JLabel();
        Saldo_pg1 = new javax.swing.JLabel();
        $ = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        enviarPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        TelefonoEnviar = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        montoEnviar = new javax.swing.JTextField();
        enviar_plata = new javax.swing.JLabel();
        enviar_plata_alerta = new javax.swing.JLabel();
        recargarPanel = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        montoRecargar = new javax.swing.JTextField();
        recargar = new javax.swing.JLabel();
        retirar = new javax.swing.JLabel();
        historialPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        editarInfoPanel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        edadEU = new javax.swing.JTextField();
        contraseñaEU = new javax.swing.JPasswordField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        usuarioEU = new javax.swing.JTextField();
        emailEU = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        DireccionEU = new javax.swing.JTextField();
        TelefonoEU = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        C_CEU = new javax.swing.JTextField();
        nombreCompletoEU = new javax.swing.JTextField();
        nombre_completo1 = new javax.swing.JLabel();
        guardarInfoButon = new javax.swing.JLabel();
        PanelLaveles = new javax.swing.JPanel();
        salir = new javax.swing.JLabel();
        historialBoton = new javax.swing.JLabel();
        cerarInicio = new javax.swing.JLabel();
        editarInfoBoton = new javax.swing.JLabel();
        dinero_inicio = new javax.swing.JLabel();
        fondo1 = new javax.swing.JLabel();
        fondoRegistro = new javax.swing.JPanel();
        Registrarse = new javax.swing.JPanel();
        logo2 = new javax.swing.JLabel();
        nombreCompletoRegistrarse = new javax.swing.JTextField();
        nombre_completo = new javax.swing.JLabel();
        C_CRegistrarse = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TelefonoRegistrarse = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DireccionRegistrarse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        emailRegistrarse = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        usuarioRegistrarse = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        edadRegistrarse = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        guardarRegistrase = new javax.swing.JButton();
        alerta_registro = new javax.swing.JLabel();
        contraseñaRegistrarse = new javax.swing.JPasswordField();
        cerarRegistro = new javax.swing.JLabel();
        fondo2 = new javax.swing.JLabel();

        textButonEstilo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        textButonEstilo.setForeground(new java.awt.Color(160, 19, 128));
        textButonEstilo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textButonEstilo.setText("jLabel19");

        logoStilo.setFont(new java.awt.Font("Berlin Sans FB", 0, 30)); // NOI18N
        logoStilo.setForeground(new java.awt.Color(144, 68, 232));
        logoStilo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoStilo.setText("AA Bank Movil");

        TextFieldEstilo.setBackground(new java.awt.Color(236, 224, 232));
        TextFieldEstilo.setText("jTextField1");

        eliminarUsuario.setBackground(textButonEstilo.getBackground());
        eliminarUsuario.setFont(textButonEstilo.getFont());
        eliminarUsuario.setForeground(textButonEstilo.getForeground());
        eliminarUsuario.setHorizontalAlignment(textButonEstilo.getHorizontalAlignment());
        eliminarUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eliminarUsuarioMouseClicked(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("AA Bank Movil");
        setBounds(new java.awt.Rectangle(0, 0, 200, 200));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(309, 510));
        getContentPane().setLayout(new java.awt.CardLayout());

        fondoLogin.setPreferredSize(new java.awt.Dimension(309, 508));
        fondoLogin.setLayout(null);

        Loguin.setOpaque(false);

        usuarioLogin.setBackground(TextFieldEstilo.getBackground());
        usuarioLogin.setFont(TextFieldEstilo.getFont());
        usuarioLogin.setForeground(TextFieldEstilo.getForeground());
        usuarioLogin.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        usuarioLogin.setText("usuario");
        usuarioLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        usuarioLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuarioLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuarioLoginMouseExited(evt);
            }
        });

        contraseñaLogin.setBackground(TextFieldEstilo.getBackground());
        contraseñaLogin.setFont(TextFieldEstilo.getFont());
        contraseñaLogin.setForeground(TextFieldEstilo.getForeground());
        contraseñaLogin.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        contraseñaLogin.setText("xxxxxxxx");
        contraseñaLogin.setToolTipText("");
        contraseñaLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contraseñaLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contraseñaLoginMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contraseñaLoginMouseExited(evt);
            }
        });

        logo1.setFont(logoStilo.getFont());
        logo1.setForeground(logoStilo.getForeground());
        logo1.setHorizontalAlignment(logoStilo.getHorizontalAlignment());
        logo1.setText(logoStilo.getText());
        logo1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Entrar1.setText("Entrar");
        Entrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Entrar1ActionPerformed(evt);
            }
        });

        Reguistrarse1.setText("Registrarse");
        Reguistrarse1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reguistrarse1ActionPerformed(evt);
            }
        });

        alerta_login.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cerarLogin.setBackground(new java.awt.Color(255, 51, 51));
        cerarLogin.setFont(textButonEstilo.getFont());
        cerarLogin.setForeground(textButonEstilo.getForeground());
        cerarLogin.setHorizontalAlignment(textButonEstilo.getHorizontalAlignment());
        cerarLogin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cerarLoginMouseDragged(evt);
            }
        });
        cerarLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerarLoginMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerarLoginMousePressed(evt);
            }
        });

        userListPanel.setVisible(false);
        panelOf();
        userListPanel.setOpaque(false);

        userList.setModel(model2);
        userList.setBorder(null);
        userList.setFont(TextFieldEstilo.getFont());
        userList.setForeground(TextFieldEstilo.getForeground());
        jScrollPane3.setViewportView(userList);

        javax.swing.GroupLayout userListPanelLayout = new javax.swing.GroupLayout(userListPanel);
        userListPanel.setLayout(userListPanelLayout);
        userListPanelLayout.setHorizontalGroup(
            userListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userListPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
        userListPanelLayout.setVerticalGroup(
            userListPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userListPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout LoguinLayout = new javax.swing.GroupLayout(Loguin);
        Loguin.setLayout(LoguinLayout);
        LoguinLayout.setHorizontalGroup(
            LoguinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoguinLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(LoguinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoguinLayout.createSequentialGroup()
                        .addComponent(logo1, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoguinLayout.createSequentialGroup()
                        .addGroup(LoguinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Entrar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Reguistrarse1, javax.swing.GroupLayout.DEFAULT_SIZE, 104, Short.MAX_VALUE))
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoguinLayout.createSequentialGroup()
                        .addGroup(LoguinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(usuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(contraseñaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(84, 84, 84))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoguinLayout.createSequentialGroup()
                        .addComponent(alerta_login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(53, 53, 53))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoguinLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userListPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(LoguinLayout.createSequentialGroup()
                .addGap(132, 132, 132)
                .addComponent(cerarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LoguinLayout.setVerticalGroup(
            LoguinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoguinLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logo1)
                .addGap(57, 57, 57)
                .addComponent(usuarioLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(contraseñaLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(Entrar1)
                .addGap(31, 31, 31)
                .addComponent(Reguistrarse1)
                .addGap(18, 18, 18)
                .addComponent(alerta_login, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userListPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addComponent(cerarLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        fondoLogin.add(Loguin);
        Loguin.setBounds(0, 0, 309, 510);

        fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ico/OIG (1).jpg"))); // NOI18N
        fondoLogin.add(fondo);
        fondo.setBounds(0, 0, 310, 510);

        getContentPane().add(fondoLogin, "card5");

        fondoInicio.setPreferredSize(new java.awt.Dimension(309, 508));
        fondoInicio.setLayout(null);

        Inicio.setOpaque(false);
        Inicio.setPreferredSize(new java.awt.Dimension(309, 510));

        nombre_pg1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        nombre_pg1.setText("Nombre");

        logo3.setFont(logoStilo.getFont());
        logo3.setForeground(logoStilo.getForeground());
        logo3.setHorizontalAlignment(logoStilo.getHorizontalAlignment());
        logo3.setText(logoStilo.getText());
        logo3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        Saldo_pg1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Saldo_pg1.setText("Saldo");

        $.setText("$:");

        jPanel2.setOpaque(false);
        jPanel2.setLayout(null);

        enviarPanel.setBackground(new java.awt.Color(255, 102, 102));
        enviarPanel.setOpaque(false);
        enviarPanel.setPreferredSize(new java.awt.Dimension(266, 184));

        jLabel11.setText("numero de telefono:");

        TelefonoEnviar.setBackground(TextFieldEstilo.getBackground());
        TelefonoEnviar.setFont(TextFieldEstilo.getFont());
        TelefonoEnviar.setForeground(TextFieldEstilo.getForeground());
        TelefonoEnviar.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        TelefonoEnviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoEnviarKeyTyped(evt);
            }
        });

        jLabel12.setText("Monto:");

        montoEnviar.setBackground(TextFieldEstilo.getBackground());
        montoEnviar.setFont(TextFieldEstilo.getFont());
        montoEnviar.setForeground(TextFieldEstilo.getForeground());
        montoEnviar.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        montoEnviar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montoEnviarKeyTyped(evt);
            }
        });

        enviar_plata.setText("Enviar");
        enviar_plata.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviar_plataMouseClicked(evt);
            }
        });

        enviar_plata_alerta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout enviarPanelLayout = new javax.swing.GroupLayout(enviarPanel);
        enviarPanel.setLayout(enviarPanelLayout);
        enviarPanelLayout.setHorizontalGroup(
            enviarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enviarPanelLayout.createSequentialGroup()
                .addGroup(enviarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(enviarPanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(enviarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(enviarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TelefonoEnviar)
                            .addGroup(enviarPanelLayout.createSequentialGroup()
                                .addComponent(montoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enviarPanelLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(enviarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, enviarPanelLayout.createSequentialGroup()
                                .addComponent(enviar_plata)
                                .addGap(42, 42, 42))
                            .addComponent(enviar_plata_alerta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(16, 16, 16))
        );
        enviarPanelLayout.setVerticalGroup(
            enviarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(enviarPanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(enviarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(TelefonoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enviar_plata_alerta, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(enviarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(montoEnviar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(enviar_plata, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(enviarPanel);
        enviarPanel.setBounds(300, 180, 270, 165);

        recargarPanel.setOpaque(false);
        recargarPanel.setPreferredSize(new java.awt.Dimension(266, 184));

        jLabel15.setText("Monto:");

        montoRecargar.setBackground(TextFieldEstilo.getBackground());
        montoRecargar.setFont(TextFieldEstilo.getFont());
        montoRecargar.setForeground(TextFieldEstilo.getForeground());
        montoRecargar.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        montoRecargar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                montoRecargarKeyTyped(evt);
            }
        });

        recargar.setText("Recargar");
        recargar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                recargarMouseClicked(evt);
            }
        });

        retirar.setText("Retirar");
        retirar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                retirarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout recargarPanelLayout = new javax.swing.GroupLayout(recargarPanel);
        recargarPanel.setLayout(recargarPanelLayout);
        recargarPanelLayout.setHorizontalGroup(
            recargarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, recargarPanelLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(retirar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(recargar)
                .addGap(48, 48, 48))
            .addGroup(recargarPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(montoRecargar, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );
        recargarPanelLayout.setVerticalGroup(
            recargarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(recargarPanelLayout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(recargarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(montoRecargar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(recargarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recargar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(retirar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel2.add(recargarPanel);
        recargarPanel.setBounds(300, 190, 270, 165);

        historialPanel.setBackground(new java.awt.Color(51, 51, 255));
        historialPanel.setOpaque(false);

        jScrollPane1.setOpaque(false);

        jList2.setFont(TextFieldEstilo.getFont());
        jList2.setForeground(TextFieldEstilo.getForeground());
        jList2.setModel(model);
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList2.setOpaque(false);
        jScrollPane1.setViewportView(jList2);

        javax.swing.GroupLayout historialPanelLayout = new javax.swing.GroupLayout(historialPanel);
        historialPanel.setLayout(historialPanelLayout);
        historialPanelLayout.setHorizontalGroup(
            historialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
            .addGroup(historialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE))
        );
        historialPanelLayout.setVerticalGroup(
            historialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
            .addGroup(historialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE))
        );

        jPanel2.add(historialPanel);
        historialPanel.setBounds(0, 390, 260, 220);

        editarInfoPanel.setBackground(new java.awt.Color(0, 102, 0));
        editarInfoPanel.setOpaque(false);

        jLabel9.setText("Edad");
        jLabel9.setToolTipText("");

        edadEU.setBackground(TextFieldEstilo.getBackground());
        edadEU.setFont(TextFieldEstilo.getFont());
        edadEU.setForeground(TextFieldEstilo.getForeground());
        edadEU.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        edadEU.setToolTipText("");
        edadEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                edadEUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                edadEUMouseExited(evt);
            }
        });
        edadEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edadEUKeyTyped(evt);
            }
        });

        contraseñaEU.setBackground(TextFieldEstilo.getBackground());
        contraseñaEU.setFont(TextFieldEstilo.getFont());
        contraseñaEU.setForeground(TextFieldEstilo.getForeground());
        contraseñaEU.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        contraseñaEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contraseñaEUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contraseñaEUMouseExited(evt);
            }
        });

        jLabel10.setText("Contaseña");
        jLabel10.setToolTipText("");

        jLabel13.setText("Usuario");
        jLabel13.setToolTipText("");

        usuarioEU.setBackground(TextFieldEstilo.getBackground());
        usuarioEU.setFont(TextFieldEstilo.getFont());
        usuarioEU.setForeground(TextFieldEstilo.getForeground());
        usuarioEU.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        usuarioEU.setToolTipText("");
        usuarioEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                usuarioEUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                usuarioEUMouseExited(evt);
            }
        });

        emailEU.setBackground(TextFieldEstilo.getBackground());
        emailEU.setFont(TextFieldEstilo.getFont());
        emailEU.setForeground(TextFieldEstilo.getForeground());
        emailEU.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        emailEU.setToolTipText("");
        emailEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                emailEUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                emailEUMouseExited(evt);
            }
        });

        jLabel14.setText("Email");
        jLabel14.setToolTipText("");

        jLabel16.setText("Direccion:");

        DireccionEU.setBackground(TextFieldEstilo.getBackground());
        DireccionEU.setFont(TextFieldEstilo.getFont());
        DireccionEU.setForeground(TextFieldEstilo.getForeground());
        DireccionEU.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        DireccionEU.setToolTipText("");
        DireccionEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DireccionEUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DireccionEUMouseExited(evt);
            }
        });

        TelefonoEU.setBackground(TextFieldEstilo.getBackground());
        TelefonoEU.setFont(TextFieldEstilo.getFont());
        TelefonoEU.setForeground(TextFieldEstilo.getForeground());
        TelefonoEU.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        TelefonoEU.setToolTipText("");
        TelefonoEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TelefonoEUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TelefonoEUMouseExited(evt);
            }
        });
        TelefonoEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoEUKeyTyped(evt);
            }
        });

        jLabel17.setText("Telefono:");

        jLabel18.setText("C.C.:");

        C_CEU.setBackground(TextFieldEstilo.getBackground());
        C_CEU.setFont(TextFieldEstilo.getFont());
        C_CEU.setForeground(TextFieldEstilo.getForeground());
        C_CEU.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        C_CEU.setToolTipText("");
        C_CEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                C_CEUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                C_CEUMouseExited(evt);
            }
        });
        C_CEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                C_CEUKeyTyped(evt);
            }
        });

        nombreCompletoEU.setBackground(TextFieldEstilo.getBackground());
        nombreCompletoEU.setFont(TextFieldEstilo.getFont());
        nombreCompletoEU.setForeground(TextFieldEstilo.getForeground());
        nombreCompletoEU.setHorizontalAlignment(TextFieldEstilo.getHorizontalAlignment());
        nombreCompletoEU.setToolTipText("");
        nombreCompletoEU.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nombreCompletoEUMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nombreCompletoEUMouseExited(evt);
            }
        });
        nombreCompletoEU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreCompletoEUKeyTyped(evt);
            }
        });

        nombre_completo1.setText("Nombre Completo");

        guardarInfoButon.setFont(textButonEstilo.getFont());
        guardarInfoButon.setForeground(textButonEstilo.getForeground());
        guardarInfoButon.setText("OK");
        guardarInfoButon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                guardarInfoButonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout editarInfoPanelLayout = new javax.swing.GroupLayout(editarInfoPanel);
        editarInfoPanel.setLayout(editarInfoPanelLayout);
        editarInfoPanelLayout.setHorizontalGroup(
            editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(editarInfoPanelLayout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(guardarInfoButon)
                .addContainerGap(153, Short.MAX_VALUE))
            .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editarInfoPanelLayout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(editarInfoPanelLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usuarioEU, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editarInfoPanelLayout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(emailEU, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarInfoPanelLayout.createSequentialGroup()
                            .addComponent(jLabel17)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(TelefonoEU, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editarInfoPanelLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(C_CEU, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(editarInfoPanelLayout.createSequentialGroup()
                            .addComponent(nombre_completo1)
                            .addGap(18, 18, 18)
                            .addComponent(nombreCompletoEU, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarInfoPanelLayout.createSequentialGroup()
                            .addComponent(jLabel16)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(DireccionEU, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarInfoPanelLayout.createSequentialGroup()
                            .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(edadEU, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                .addComponent(contraseñaEU))))
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        editarInfoPanelLayout.setVerticalGroup(
            editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, editarInfoPanelLayout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(guardarInfoButon)
                .addContainerGap())
            .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(editarInfoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nombreCompletoEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nombre_completo1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(C_CEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel18))
                    .addGap(18, 18, 18)
                    .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TelefonoEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17))
                    .addGap(18, 18, 18)
                    .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(DireccionEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16))
                    .addGap(18, 18, 18)
                    .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14))
                    .addGap(18, 18, 18)
                    .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(usuarioEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13))
                    .addGap(18, 18, 18)
                    .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(contraseñaEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(editarInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(edadEU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        jPanel2.add(editarInfoPanel);
        editarInfoPanel.setBounds(0, 390, 260, 350);

        PanelLaveles.setOpaque(false);
        PanelLaveles.setLayout(new java.awt.GridLayout(1, 0));

        salir.setFont(textButonEstilo.getFont());
        salir.setForeground(textButonEstilo.getForeground());
        salir.setHorizontalAlignment(textButonEstilo.getHorizontalAlignment());
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                salirMousePressed(evt);
            }
        });
        PanelLaveles.add(salir);

        historialBoton.setFont(textButonEstilo.getFont());
        historialBoton.setForeground(textButonEstilo.getForeground());
        historialBoton.setHorizontalAlignment(textButonEstilo.getHorizontalAlignment());
        historialBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historialBotonMouseClicked(evt);
            }
        });
        PanelLaveles.add(historialBoton);

        cerarInicio.setBackground(new java.awt.Color(255, 51, 51));
        cerarInicio.setFont(textButonEstilo.getFont());
        cerarInicio.setForeground(textButonEstilo.getForeground());
        cerarInicio.setHorizontalAlignment(textButonEstilo.getHorizontalAlignment());
        cerarInicio.setToolTipText("");
        cerarInicio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cerarInicioMouseDragged(evt);
            }
        });
        cerarInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerarInicioMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerarInicioMousePressed(evt);
            }
        });
        PanelLaveles.add(cerarInicio);

        editarInfoBoton.setFont(textButonEstilo.getFont());
        editarInfoBoton.setForeground(textButonEstilo.getForeground());
        editarInfoBoton.setHorizontalAlignment(textButonEstilo.getHorizontalAlignment());
        editarInfoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editarInfoBotonMouseClicked(evt);
            }
        });
        PanelLaveles.add(editarInfoBoton);

        dinero_inicio.setFont(textButonEstilo.getFont());
        dinero_inicio.setForeground(textButonEstilo.getForeground());
        dinero_inicio.setHorizontalAlignment(textButonEstilo.getHorizontalAlignment());
        dinero_inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dinero_inicioMouseClicked(evt);
            }
        });
        PanelLaveles.add(dinero_inicio);

        javax.swing.GroupLayout InicioLayout = new javax.swing.GroupLayout(Inicio);
        Inicio.setLayout(InicioLayout);
        InicioLayout.setHorizontalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(InicioLayout.createSequentialGroup()
                        .addComponent($)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Saldo_pg1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombre_pg1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addComponent(PanelLaveles, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InicioLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(logo3, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        InicioLayout.setVerticalGroup(
            InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InicioLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre_pg1)
                    .addComponent(Saldo_pg1)
                    .addComponent($))
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelLaveles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(InicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(InicioLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(logo3)
                    .addContainerGap(458, Short.MAX_VALUE)))
        );

        fondoInicio.add(Inicio);
        Inicio.setBounds(0, 0, 309, 510);

        fondo1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ico/OIG (1).jpg"))); // NOI18N
        fondoInicio.add(fondo1);
        fondo1.setBounds(0, 0, 310, 510);

        getContentPane().add(fondoInicio, "card5");

        fondoRegistro.setLayout(null);

        Registrarse.setOpaque(false);
        Registrarse.setPreferredSize(new java.awt.Dimension(309, 510));

        logo2.setFont(logoStilo.getFont());
        logo2.setForeground(logoStilo.getForeground());
        logo2.setHorizontalAlignment(logoStilo.getHorizontalAlignment());
        logo2.setText(logoStilo.getText());
        logo2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        nombreCompletoRegistrarse.setToolTipText("");
        nombreCompletoRegistrarse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                nombreCompletoRegistrarseKeyTyped(evt);
            }
        });

        nombre_completo.setText("Nombre Completo");

        C_CRegistrarse.setToolTipText("");
        C_CRegistrarse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                C_CRegistrarseKeyTyped(evt);
            }
        });

        jLabel2.setText("C.C.:");

        TelefonoRegistrarse.setToolTipText("");
        TelefonoRegistrarse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TelefonoRegistrarseKeyTyped(evt);
            }
        });

        jLabel3.setText("Telefono:");

        DireccionRegistrarse.setToolTipText("");

        jLabel4.setText("Direccion:");

        emailRegistrarse.setToolTipText("");

        jLabel5.setText("Email");
        jLabel5.setToolTipText("");

        usuarioRegistrarse.setToolTipText("");

        jLabel6.setText("Usuario");
        jLabel6.setToolTipText("");

        jLabel7.setText("Contaseña");
        jLabel7.setToolTipText("");

        edadRegistrarse.setToolTipText("");
        edadRegistrarse.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                edadRegistrarseKeyTyped(evt);
            }
        });

        jLabel8.setText("Edad");
        jLabel8.setToolTipText("");

        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        guardarRegistrase.setText("Guardar");
        guardarRegistrase.setMaximumSize(new java.awt.Dimension(76, 23));
        guardarRegistrase.setMinimumSize(new java.awt.Dimension(76, 23));
        guardarRegistrase.setPreferredSize(new java.awt.Dimension(76, 23));
        guardarRegistrase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarRegistraseActionPerformed(evt);
            }
        });

        alerta_registro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        cerarRegistro.setBackground(new java.awt.Color(255, 51, 51));
        cerarRegistro.setFont(textButonEstilo.getFont());
        cerarRegistro.setForeground(textButonEstilo.getForeground());
        cerarRegistro.setHorizontalAlignment(textButonEstilo.getHorizontalAlignment());
        cerarRegistro.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                cerarRegistroMouseDragged(evt);
            }
        });
        cerarRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerarRegistroMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cerarRegistroMousePressed(evt);
            }
        });

        javax.swing.GroupLayout RegistrarseLayout = new javax.swing.GroupLayout(Registrarse);
        Registrarse.setLayout(RegistrarseLayout);
        RegistrarseLayout.setHorizontalGroup(
            RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarseLayout.createSequentialGroup()
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistrarseLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(logo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(RegistrarseLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addComponent(cancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(guardarRegistrase, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usuarioRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarseLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TelefonoRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(C_CRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(RegistrarseLayout.createSequentialGroup()
                                .addComponent(nombre_completo)
                                .addGap(18, 18, 18)
                                .addComponent(nombreCompletoRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarseLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(DireccionRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(alerta_registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegistrarseLayout.createSequentialGroup()
                                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(edadRegistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(contraseñaRegistrarse))))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(RegistrarseLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cerarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistrarseLayout.setVerticalGroup(
            RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistrarseLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(alerta_registro, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreCompletoRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nombre_completo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(C_CRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelefonoRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DireccionRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(usuarioRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(contraseñaRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edadRegistrarse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(RegistrarseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelar)
                    .addComponent(guardarRegistrase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cerarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3))
        );

        fondoRegistro.add(Registrarse);
        Registrarse.setBounds(0, 0, 309, 510);

        fondo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI/ico/OIG (1).jpg"))); // NOI18N
        fondoRegistro.add(fondo2);
        fondo2.setBounds(0, 0, 310, 510);

        getContentPane().add(fondoRegistro, "card5");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    public void limpiar_jtextField(JTextField jTextField) {
         
        jTextField.setText("");
    }
    public void panelOf() {
        if (Usuario.usuarios().size()>0) {
            userListPanel.setVisible(true);
            model2.removeAllElements();
            for (int i = 0; i < Usuario.usuarios().size(); i++) {
                
                model2.add(i,Usuario.usuarios().get(i));
            }
            
        } else {
            userListPanel.setVisible(false);
            
        }
    }
    private void Reguistrarse1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reguistrarse1ActionPerformed
        // TODO add your handling code here:
        limpiar_jtextField(nombreCompletoRegistrarse);
        limpiar_jtextField(C_CRegistrarse);
        limpiar_jtextField(TelefonoRegistrarse);
        limpiar_jtextField(DireccionRegistrarse);
        limpiar_jtextField(emailRegistrarse);
        limpiar_jtextField(usuarioRegistrarse);
        limpiar_jtextField(contraseñaRegistrarse);
        limpiar_jtextField(edadRegistrarse);
        fondoLogin.setVisible(false);
        fondoRegistro.setVisible(true);
    }//GEN-LAST:event_Reguistrarse1ActionPerformed

    private void Entrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Entrar1ActionPerformed
         // TODO add your handling code here:
         // Usuario2 user = new Usuario2();
        enviarPanel.setBounds(300, enviarPanel.getY(), enviarPanel.getWidth(), enviarPanel.getHeight());
        recargarPanel.setBounds(300, recargarPanel.getY(), recargarPanel.getWidth(), recargarPanel.getHeight());
        if(Usuario.usuarios().contains(usuarioLogin.getText())){
            user = new Usuario(usuarioLogin.getText());
            if(Arrays.equals(user.getContraseña(),contraseñaLogin.getPassword())){
                fondoLogin.setVisible(false);
                fondoInicio.setVisible(true);
                nombre_pg1.setText(user.getNombre_completo());
                Saldo_pg1.setText(user.getSaldoFormat());
    //            historialPanel.setBounds(0, 390, 260, 220);
                enviarPanel.setBounds(300, 180, 270, 165);
                recargarPanel.setBounds(300, 180, 270, 165);
    //            editarInfoPanel.setBounds(0, 390, 260, 350);
    
                usuarioLogin.setText("usuario");
                contraseñaLogin.setText("xxxxx");
                alerta_login.setText("");
            }else{
            alerta_login.setText("El Usaurio o la contraseña son incorectos");
            alerta_login.setForeground(Color.RED);
        }
        }else{
            alerta_login.setText("El Usaurio o la contraseña son incorectos");
            alerta_login.setForeground(Color.RED);
        }
    }//GEN-LAST:event_Entrar1ActionPerformed

    private void guardarRegistraseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarRegistraseActionPerformed
        // TODO add your handling code here
        // Usuario2 user = new Usuario2();

        if (!(C_CRegistrarse.getText().equals("")&&TelefonoRegistrarse.getText().equals("")&&DireccionRegistrarse.getText().equals("")&&emailRegistrarse.getText().equals("")&&usuarioRegistrarse.getText().equals("")&&edadRegistrarse.getText().equals(""))) {
            if (!Usuario.usuarios().contains(usuarioRegistrarse.getText())) {
                user = new Usuario();
                user.setNombre_completo(nombreCompletoRegistrarse.getText());
                user.setEdad(Integer.parseInt(edadRegistrarse.getText()));
                user.setcC(Long.parseLong(C_CRegistrarse.getText()));
                user.setTelefono(Long.parseLong(TelefonoRegistrarse.getText()));
                user.setDireccion(DireccionRegistrarse.getText());
                user.setEmail(emailRegistrarse.getText());
                user.setUsuario(usuarioRegistrarse.getText());
                user.setContraseña(contraseñaRegistrarse.getPassword());
                user.guardar();
                
                nombre_pg1.setText(user.getNombre_completo());
                Saldo_pg1.setText(user.getSaldoFormat());
                
                fondoRegistro.setVisible(false);
                fondoInicio.setVisible(true);
                
            } else {
                alerta_registro.setForeground(Color.RED);
                alerta_registro.setText("El usuario ya existe");
    
            }
        }else{
            
            alerta_registro.setForeground(Color.RED);
            alerta_registro.setText("Faltan campos por llenar");
        }
    }//GEN-LAST:event_guardarRegistraseActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        // TODO add your handling code here:
        alerta_login.setText("");  
        fondoRegistro.setVisible(false);
        fondoLogin.setVisible(true);
        panelOf();
    }//GEN-LAST:event_cancelarActionPerformed

    private void salirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMousePressed
        // TODO add your handling code here:
        fondoLogin.setVisible(true);
        fondoInicio.setVisible(false);
        panelOf();
        
    }//GEN-LAST:event_salirMousePressed

    private void Usuario1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Usuario1KeyPressed
        // TODO add your handling code here:
        limpiar_jtextField(usuarioLogin);
        
    }//GEN-LAST:event_Usuario1KeyPressed

    private void dinero_inicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dinero_inicioMouseClicked
        enviar_plata_alerta.setText("");
        if (editarInfoPanel.getY()==30) {
            slide.jPanelYAbajo(30, 390, 10, 5, editarInfoPanel);
        }
        if(historialPanel.getY()==160){
                    slide.jPanelYAbajo(160, 390, 10,5, historialPanel);
                }
        switch (plataStado) {
            case 0:
                slide.jPanelXIzquierda(300, 5, 10, 5, enviarPanel);
                plataStado=1;
                break;
            case 1:
                montoEnviar.setText("");
                TelefonoEnviar.setText("");
                slide.jPanelXDerecha(5, 300, 10, 5, enviarPanel);
                slide.jPanelXIzquierda(300, 5, 10, 5, recargarPanel);
                plataStado=2;
                break;
            case 2:
                montoRecargar.setText("");
                slide.jPanelXDerecha(5, 300, 10, 5, recargarPanel);
                plataStado=0;
                break;
        
            default:
                break;
        }
        
    }//GEN-LAST:event_dinero_inicioMouseClicked

    private void enviar_plataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviar_plataMouseClicked

// TODO add your handling code here:
        if (Usuario.telefonos().contains(Long.parseLong(TelefonoEnviar.getText()))) {
            int index = Usuario.telefonos().indexOf(Long.parseLong(TelefonoEnviar.getText()));
            Usuario user2 = new Usuario(Usuario.usuarios().get(index));
            if (user.setSaldo((Long.parseLong(montoEnviar.getText()))*(-1))) {
                user2.setSaldo(Long.parseLong(montoEnviar.getText()));
                Saldo_pg1.setText(user.getSaldoFormat());
                user.guardar();
                user2.guardar();
                enviar_plata_alerta.setText("Envio Exitoso");

            } else {
            enviar_plata_alerta.setText("No tiene recursos suficientes");
            enviar_plata_alerta.setForeground(Color.RED);
            }
        } else {
            enviar_plata_alerta.setText("Telefono inexistente");
            enviar_plata_alerta.setForeground(Color.RED);
        }
        
        
    }//GEN-LAST:event_enviar_plataMouseClicked

    private void usuarioLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioLoginMouseEntered
        // TODO add your handling code here:
        if (usuarioLogin.getText().compareTo("usuario")==0) {
            usuarioLogin.setText("");
        }
    }//GEN-LAST:event_usuarioLoginMouseEntered

    private void usuarioLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioLoginMouseExited
        // TODO add your handling code here:
        if (usuarioLogin.getText().compareTo("")==0) {
            usuarioLogin.setText("usuario");
        }
    }//GEN-LAST:event_usuarioLoginMouseExited
    
    private void contraseñaLoginMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaLoginMouseEntered
        // TODO add your handling code here:
        char contra[] = contraseñaLogin.getPassword();
        char compare[] = ("xxxxxxxx").toCharArray();
        int total_vueltas=0;
        int total_compar=0;

        if (contra.length<compare.length) {
            total_vueltas=contra.length;
        }else if(compare.length<contra.length){
            total_vueltas=compare.length;
        }else{
            total_vueltas=compare.length;
        }


        for (int i = 0; i < total_vueltas; i++) {
            if (contra[i]==compare[i]) {
                total_compar++;
            }
        }
        if (total_compar==total_vueltas) {
            contraseñaLogin.setText("");
        }
        
    }//GEN-LAST:event_contraseñaLoginMouseEntered

    private void contraseñaLoginMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaLoginMouseExited
        // TODO add your handling code here:
        char contra[] = contraseñaLogin.getPassword();
        if (!(contra.length>0)) {
            
            contraseñaLogin.setText("xxxxxxxx");
        }
    }//GEN-LAST:event_contraseñaLoginMouseExited

    private void historialBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialBotonMouseClicked
        // TODO add your handling code here:
        //si el panel de editar informacion esta desplegado se contrae
        model.removeAllElements();
        for (int i = 0; i < user.historialCambios().size(); i++) {
            
            model.add(i, String.join("-",user.historialCambios().get(i)));
        }
        if (editarInfoPanel.getY()==30) {
            slide.jPanelYAbajo(30, 390, 10, 5, editarInfoPanel);
        }
        if (historialPanel.getY()==160) {
            
            slide.jPanelYAbajo(160, 390, 10,5, historialPanel);
        } else {
            
            slide.jPanelYArriba(390, 160, 10,5, historialPanel);
        }
        if (enviarPanel.getBounds().x==5) {
            
            slide.jPanelXDerecha(5, 300, 10, 5, enviarPanel);
        }
        if (recargarPanel.getBounds().x==5) {
            
            slide.jPanelXDerecha(5, 300, 10, 5, recargarPanel);
        }
        
        
    }//GEN-LAST:event_historialBotonMouseClicked

    private void recargarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_recargarMouseClicked
        // TODO add your handling code here:
        user.setSaldo(Long.parseLong(montoRecargar.getText()));
        user.guardar();
        Saldo_pg1.setText(user.getSaldoFormat());
        montoRecargar.setText("");

    }//GEN-LAST:event_recargarMouseClicked

    private void editarInfoBotonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editarInfoBotonMouseClicked
        // TODO add your handling code here:
        if (recargarPanel.getX()==5) {
            
            slide.jPanelXDerecha(5, 300, 10, 5, recargarPanel);
        }
        if (enviarPanel.getX()==5) {
            
            slide.jPanelXDerecha(5, 300, 10, 5, enviarPanel);
        }
        //si el panel de historial esta desplegado se contrae
        if(historialPanel.getY()==160){
                    slide.jPanelYAbajo(160, 390, 10,5, historialPanel);
                }
        //si el panel de editar informacion esta desplegado se contrae
        if (editarInfoPanel.getY()==30) {
            slide.jPanelYAbajo(30, 390, 10, 5, editarInfoPanel);
            
        } else {
            slide.jPanelYArriba(390, 30, 10, 5, editarInfoPanel);
            
        }
        if (!(editarInfoPanel.getY()==30)) {
            nombreCompletoEU.setText(user.getNombre_completo());
            C_CEU.setText(Long.toString(user.getcC()));
            TelefonoEU.setText(Long.toString(user.getTelefono()));
            DireccionEU.setText(user.getDireccion());
            emailEU.setText(user.getEmail());
            usuarioEU.setText(user.getUsuario());
            edadEU.setText(Integer.toString(user.getEdad()));
            
            char[] con = user.getContraseña();
            String con2="";
            for (int i = 0; i < con.length; i++) {
                
                con2 += ""+con[i];
            }
            contraseñaEU.setText(con2);
    
        }
        
    }//GEN-LAST:event_editarInfoBotonMouseClicked

    private void guardarInfoButonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_guardarInfoButonMouseClicked
        // TODO add your handling code here:
        slide.jPanelYAbajo(editarInfoPanel.getY(), 390, 10, 5, editarInfoPanel);
        user.setUsuario( usuarioEU.getText());
        user.setcC( Long.parseLong(C_CEU.getText()));
        user.setTelefono( Long.parseLong(TelefonoEU.getText()));
        user.setDireccion( DireccionEU.getText());
        user.setEmail( emailEU.getText());
        user.setEdad( Integer.parseInt(edadEU.getText()));
        user.setContraseña( contraseñaEU.getPassword());
        user.setNombre_completo( nombreCompletoEU.getText());
        user.guardar();
        nombre_pg1.setText(user.getNombre_completo());

        
    }//GEN-LAST:event_guardarInfoButonMouseClicked

    private void nombreCompletoEUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreCompletoEUMouseEntered
        // TODO add your handling code here:
        if (nombreCompletoEU.getText().compareTo(user.getNombre_completo())==0) {
            nombreCompletoEU.setText("");
        }
    }//GEN-LAST:event_nombreCompletoEUMouseEntered

    private void nombreCompletoEUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombreCompletoEUMouseExited
        // TODO add your handling code here:
        if (nombreCompletoEU.getText().compareTo("")==0) {
            nombreCompletoEU.setText(user.getNombre_completo());
        }
    }//GEN-LAST:event_nombreCompletoEUMouseExited

    private void C_CEUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_CEUMouseEntered
        // TODO add your handling code here:
        if (C_CEU.getText().compareTo(Long.toString(user.getcC()))==0) {
            C_CEU.setText("");
        }
    }//GEN-LAST:event_C_CEUMouseEntered

    private void C_CEUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C_CEUMouseExited
        // TODO add your handling code here:
        if (C_CEU.getText().compareTo("")==0) {
            C_CEU.setText(Long.toString(user.getcC()));
        }
    }//GEN-LAST:event_C_CEUMouseExited

    private void TelefonoEUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelefonoEUMouseEntered
        // TODO add your handling code here:
        if (TelefonoEU.getText().compareTo(Long.toString(user.getTelefono()))==0) {
            TelefonoEU.setText("");
        }

    }//GEN-LAST:event_TelefonoEUMouseEntered

    private void TelefonoEUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TelefonoEUMouseExited
        // TODO add your handling code here:
        if (TelefonoEU.getText().compareTo("")==0) {
            TelefonoEU.setText(Long.toString(user.getTelefono()));
        }
    }//GEN-LAST:event_TelefonoEUMouseExited

    private void DireccionEUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DireccionEUMouseEntered
        // TODO add your handling code here:
        if (DireccionEU.getText().compareTo(user.getDireccion())==0) {
            DireccionEU.setText("");
        }
        
    }//GEN-LAST:event_DireccionEUMouseEntered

    private void DireccionEUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DireccionEUMouseExited
        // TODO add your handling code here:
        if (DireccionEU.getText().compareTo("")==0) {
            DireccionEU.setText(user.getDireccion());
        }
    }//GEN-LAST:event_DireccionEUMouseExited

    private void emailEUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailEUMouseEntered
        // TODO add your handling code here:
        if (emailEU.getText().compareTo(user.getEmail())==0) {
            emailEU.setText("");
        }
    }//GEN-LAST:event_emailEUMouseEntered

    private void emailEUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_emailEUMouseExited
        // TODO add your handling code here:
        if (emailEU.getText().compareTo("")==0) {
            emailEU.setText(user.getEmail());
        }
    }//GEN-LAST:event_emailEUMouseExited

    private void usuarioEUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioEUMouseEntered
        // TODO add your handling code here:
        // String useString = user.getUser(nombre_pg1.getText());
        if (usuarioEU.getText().compareTo(user.getUsuario())==0) {
            usuarioEU.setText("");
        }
    }//GEN-LAST:event_usuarioEUMouseEntered

    private void usuarioEUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usuarioEUMouseExited
        // TODO add your handling code here:
        if (usuarioEU.getText().compareTo("")==0) {
            usuarioEU.setText(user.getUsuario());
        }
    }//GEN-LAST:event_usuarioEUMouseExited

    private void contraseñaEUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaEUMouseEntered
        // TODO add your handling code here:
        if (Arrays.equals(contraseñaEU.getPassword(), user.getContraseña())) {
            contraseñaEU.setText("");
        }
    }//GEN-LAST:event_contraseñaEUMouseEntered

    private void contraseñaEUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contraseñaEUMouseExited
        // TODO add your handling code here:
        if (Arrays.equals(contraseñaEU.getPassword(), "".toCharArray())) {
            contraseñaEU.setText(new String(user.getContraseña()));
        }      
    }//GEN-LAST:event_contraseñaEUMouseExited

    private void edadEUMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edadEUMouseEntered
        // TODO add your handling code here:
        if (edadEU.getText().compareTo(Integer.toString(user.getEdad()))==0) {
            edadEU.setText("");
        }
    }//GEN-LAST:event_edadEUMouseEntered

    private void edadEUMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_edadEUMouseExited
        // TODO add your handling code here:
        if (edadEU.getText().compareTo("")==0) {
            edadEU.setText(Integer.toString(user.getEdad()));
        }
    }//GEN-LAST:event_edadEUMouseExited

    private void cerarInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerarInicioMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerarInicioMouseClicked

    private void cerarInicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerarInicioMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX()+127;
        yMouse = evt.getY()+473;
    }//GEN-LAST:event_cerarInicioMousePressed

    private void cerarInicioMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerarInicioMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_cerarInicioMouseDragged

    private void cerarLoginMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerarLoginMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_cerarLoginMouseDragged

    private void cerarLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerarLoginMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerarLoginMouseClicked

    private void cerarLoginMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerarLoginMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX()+127;
        yMouse = evt.getY()+473;
    }//GEN-LAST:event_cerarLoginMousePressed

    private void cerarRegistroMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerarRegistroMouseDragged
        // TODO add your handling code here:
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_cerarRegistroMouseDragged

    private void cerarRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerarRegistroMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_cerarRegistroMouseClicked


    private void cerarRegistroMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerarRegistroMousePressed
        // TODO add your handling code here:
        xMouse = evt.getX()+127;
        yMouse = evt.getY()+473;
    }//GEN-LAST:event_cerarRegistroMousePressed

    private void nombreCompletoRegistrarseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreCompletoRegistrarseKeyTyped
        // TODO add your handling code here:

        int key = evt.getKeyChar();;
        boolean letras = key>=65 && key<=90 || key>=97 && key<=122 || key == 32 ;

        if (!letras) {
            evt.consume();
        }
        if(nombreCompletoRegistrarse.getText().length()>=25){
            evt.consume();
        }
        
    }//GEN-LAST:event_nombreCompletoRegistrarseKeyTyped

    private void C_CRegistrarseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_C_CRegistrarseKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key<=57 ;

        if (!numeros || C_CRegistrarse.getText().length()>=10) {
            evt.consume();
        }
    }//GEN-LAST:event_C_CRegistrarseKeyTyped

    private void TelefonoRegistrarseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoRegistrarseKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key<=57 ;

        if (!numeros || TelefonoRegistrarse.getText().length()>=10) {
            evt.consume();
        }
    }//GEN-LAST:event_TelefonoRegistrarseKeyTyped

    private void edadRegistrarseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edadRegistrarseKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key<=57 ;

        if (!numeros || edadRegistrarse.getText().length()>=2) {
            evt.consume();
        }
    }//GEN-LAST:event_edadRegistrarseKeyTyped

    private void TelefonoEnviarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoEnviarKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key<=57 ;

        if (!numeros || TelefonoEnviar.getText().length()>=10) {
            evt.consume();
        }
    }//GEN-LAST:event_TelefonoEnviarKeyTyped

    private void montoEnviarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoEnviarKeyTyped
        // TODO add your handling code here:
       int key = evt.getKeyChar();
        boolean numeros = key>=48 && key<=57 ;
        boolean letras = key>=65 && key<=90 || key>=97 && key<=122;

        if (letras) {
            evt.consume();
        }

        if (!numeros ) {
            evt.consume();
        }
        if( TelefonoRegistrarse.getText().length()>=10){
        }
    }//GEN-LAST:event_montoEnviarKeyTyped

    private void montoRecargarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_montoRecargarKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key<=57 ;
        boolean letras = key>=65 && key<=90 || key>=97 && key<=122;

        if (letras) {
            evt.consume();
        }

        if (!numeros ) {
            evt.consume();
        }
        if( TelefonoRegistrarse.getText().length()>=10){
        }
    }//GEN-LAST:event_montoRecargarKeyTyped

    private void nombreCompletoEUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nombreCompletoEUKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean letras = key>=65 && key<=90 || key>=97 && key<=122 || key == 32;
        System.out.println(evt.getKeyCode());
        if (!letras) {
            evt.consume();
        }
        if(nombreCompletoRegistrarse.getText().length()>=25){
            evt.consume();
        }
    }//GEN-LAST:event_nombreCompletoEUKeyTyped

    private void C_CEUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_C_CEUKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key<=57 ;

        if (!numeros || TelefonoRegistrarse.getText().length()>=10) {
            evt.consume();
        }
    }//GEN-LAST:event_C_CEUKeyTyped

    private void TelefonoEUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TelefonoEUKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key<=57 ;

        if (!numeros || TelefonoRegistrarse.getText().length()>=10) {
            evt.consume();
        }
    }//GEN-LAST:event_TelefonoEUKeyTyped

    private void edadEUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_edadEUKeyTyped
        // TODO add your handling code here:
        int key = evt.getKeyChar();
        boolean numeros = key>=48 && key<=57 ;

        if (!numeros || edadRegistrarse.getText().length()>=2) {
            evt.consume();
        }
    }//GEN-LAST:event_edadEUKeyTyped

    private void retirarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_retirarMouseClicked
        // TODO add your handling code here:
        user.setSaldo((Integer.parseInt(montoRecargar.getText()))*(-1));
        user.guardar();
        Saldo_pg1.setText(user.getSaldoFormat());
        montoRecargar.setText("");
    }//GEN-LAST:event_retirarMouseClicked

    private void eliminarUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eliminarUsuarioMouseClicked
        // TODO add your handling code here:
        System.out.println(userList.getSelectedValue());
        Usuario.eliminar(userList.getSelectedValue());
        panelOf();
    }//GEN-LAST:event_eliminarUsuarioMouseClicked

    private void imgLabel(JLabel jLabel, String pach) {
        ImageIcon imageIcon = new ImageIcon(pach);
        Image image = imageIcon.getImage().getScaledInstance(35, 35, Image.SCALE_SMOOTH);
        imageIcon = new ImageIcon(image); 
        jLabel.setIcon(imageIcon);
        repaint(); 
    }

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel $;
    private javax.swing.JTextField C_CEU;
    private javax.swing.JTextField C_CRegistrarse;
    private javax.swing.JTextField DireccionEU;
    private javax.swing.JTextField DireccionRegistrarse;
    private javax.swing.JButton Entrar1;
    private javax.swing.JPanel Inicio;
    private javax.swing.JPanel Loguin;
    private javax.swing.JPanel PanelLaveles;
    private javax.swing.JPanel Registrarse;
    private javax.swing.JButton Reguistrarse1;
    private javax.swing.JLabel Saldo_pg1;
    private javax.swing.JTextField TelefonoEU;
    private javax.swing.JTextField TelefonoEnviar;
    private javax.swing.JTextField TelefonoRegistrarse;
    private javax.swing.JTextField TextFieldEstilo;
    private javax.swing.JLabel alerta_login;
    private javax.swing.JLabel alerta_registro;
    private javax.swing.JButton cancelar;
    private javax.swing.JLabel cerarInicio;
    private javax.swing.JLabel cerarLogin;
    private javax.swing.JLabel cerarRegistro;
    private javax.swing.JPasswordField contraseñaEU;
    private javax.swing.JPasswordField contraseñaLogin;
    private javax.swing.JPasswordField contraseñaRegistrarse;
    private javax.swing.JLabel dinero_inicio;
    private javax.swing.JTextField edadEU;
    private javax.swing.JTextField edadRegistrarse;
    private javax.swing.JLabel editarInfoBoton;
    private javax.swing.JPanel editarInfoPanel;
    private javax.swing.JLabel eliminarUsuario;
    private javax.swing.JTextField emailEU;
    private javax.swing.JTextField emailRegistrarse;
    private javax.swing.JPanel enviarPanel;
    private javax.swing.JLabel enviar_plata;
    private javax.swing.JLabel enviar_plata_alerta;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo1;
    private javax.swing.JLabel fondo2;
    private javax.swing.JPanel fondoInicio;
    private javax.swing.JPanel fondoLogin;
    private javax.swing.JPanel fondoRegistro;
    private javax.swing.JLabel guardarInfoButon;
    private javax.swing.JButton guardarRegistrase;
    private javax.swing.JLabel historialBoton;
    private javax.swing.JPanel historialPanel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel logo1;
    private javax.swing.JLabel logo2;
    private javax.swing.JLabel logo3;
    private javax.swing.JLabel logoStilo;
    private javax.swing.JTextField montoEnviar;
    private javax.swing.JTextField montoRecargar;
    private javax.swing.JTextField nombreCompletoEU;
    private javax.swing.JTextField nombreCompletoRegistrarse;
    private javax.swing.JLabel nombre_completo;
    private javax.swing.JLabel nombre_completo1;
    private javax.swing.JLabel nombre_pg1;
    private javax.swing.JLabel recargar;
    private javax.swing.JPanel recargarPanel;
    private javax.swing.JLabel retirar;
    private javax.swing.JLabel salir;
    private javax.swing.JLabel textButonEstilo;
    private javax.swing.JList<String> userList;
    private javax.swing.JPanel userListPanel;
    private javax.swing.JTextField usuarioEU;
    private javax.swing.JTextField usuarioLogin;
    private javax.swing.JTextField usuarioRegistrarse;
    // End of variables declaration//GEN-END:variables
}
